### ISSUE TITLE
openssl related issues

### ISSUE THREAD

**Issue by a572651459** [alipay/quic-lb#13]
build error, Is it a problem with openssl version?
![image](https://user-images.githubusercontent.com/34877312/156961478-c69f3707-c9a5-40f7-bc8a-59bf813ab851.png)

**Comment by Neo-ZK** [comment]
Is `SSL_set_quic_use_legacy_codepoint` your custom define function, it seems there is nothing about this function in my own fork repo(ngtcp2)

**Comment by a572651459** [comment]
After following the README.rst in ngtcp2，the file examples/tls_client_session_openssl.cc file will be generated，and the function SSL_set_quic_use_legacy_codepoint is not my custom

**Comment by Neo-ZK** [comment]
Maybe you are using this cmd `git clone https://github.com/ngtcp2/ngtcp2`, please convert to `git clone https://github.com/william-zk/ngtcp2/tree/master`

Or you can add this change to ngtcp2(https://github.com/william-zk/ngtcp2/commit/dd278e76c5522bdc64f4d8937f80671073143e6d)

**Comment by a572651459** [comment]
convert to https://github.com/william-zk/ngtcp2 , The master branch still doesn't work
![image](https://user-images.githubusercontent.com/34877312/156984477-826a7c8d-bdb6-43f9-8364-aa2873c77891.png)
![image](https://user-images.githubusercontent.com/34877312/156984486-ccce8444-7246-440a-a28c-ad49a0814016.png)

**Comment by Neo-ZK** [comment]
Please convert your `nghttp3` to branch `draft-29` and recompile it

**Comment by a572651459** [comment]
still have some error in  william-zk/ngtcp2 master branch
![image](https://user-images.githubusercontent.com/34877312/156987943-1053e996-baab-477b-bdd1-1b1970c53f2e.png)

**Comment by Neo-ZK** [comment]
Sorry, some code was omitted when committing, please pull `william-zk/ngtcp2 master branch` and have another try

**Comment by Neo-ZK** [comment]
And later I will add this commit to the nearest version of ngtcp2 and update README, thanks for your information

**Comment by a572651459** [comment]
Thank you for your technical support

**Comment by a572651459** [comment]
大佬，有联系方式吗，还有些问题想请教一下？

**Comment by Neo-ZK** [comment]
相关问题可以直接联系我的邮箱`william.zk@antgroup.com`
